apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

patches:
  # Override configmap for local dev
  - target:
      kind: ConfigMap
      name: api-config
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: api-config
      data:
        NODE_ENV: "development"
        GOOGLE_CALLBACK_URL: "http://localhost:8090/v1/auth/google/callback"
        WEB_ORIGIN: "http://localhost:3000"

  # Override ingress for localhost
  - target:
      kind: Ingress
      name: api-ingress
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: api-ingress
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: null
      spec:
        tls: []
        rules:
          - host: localhost
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: api
                      port:
                        number: 3001
