apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: fs-suite
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: fs-suite
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
