import { Injectable } from '@nestjs/common';

import ptVfrData from './data/pt-vfr.json';

// ---------- Dataset shapes (produced by scripts/refresh-pt-vfr.ts) ----------

export interface PtVfrRoutePoint {
  name: string;
  lat: number;
  lon: number;
}

export interface PtVfrRouteLeg {
  fromIdx: number;
  toIdx: number;
  /** MAG course flying the leg in listed order (null = direction not authorized). */
  courseAtoB: number | null;
  /** MAG course flying the leg against listed order (null = direction not authorized). */
  courseBtoA: number | null;
  upperFt: number | null;
  lowerFt: number | null;
}

export interface PtVfrRoute {
  id: string;
  name: string;
  /** TMA grouping: Lisboa | Porto | Faro */
  area: string;
  points: PtVfrRoutePoint[];
  legs: PtVfrRouteLeg[];
}

export interface PtVfrPoint {
  name: string;
  lat: number;
  lon: number;
  /** Route names this point belongs to, as published in ENR 4.4. */
  routes: string[];
}

export interface PtVfrRoutesResponse {
  source: string;
  sourceUrl: string;
  effectiveDate: string | null;
  routes: PtVfrRoute[];
}

export interface PtVfrPointsResponse {
  source: string;
  sourceUrl: string;
  effectiveDate: string | null;
  points: PtVfrPoint[];
}

/**
 * Serves the curated Portugal VFR dataset (NAV Portugal eVFR — ENR 3.5 VFR
 * tunnels/routes and ENR 4.4 visual reporting points). The dataset is a
 * versioned JSON generated by `pnpm --filter @fs-suite/api pt-vfr:refresh` on
 * AIRAC amendments — there is no runtime scraping of ais.nav.pt.
 */
@Injectable()
export class PtVfrService {
  private readonly data = ptVfrData as unknown as {
    source: string;
    sourceUrl: string;
    effectiveDate: string | null;
    routes: PtVfrRoute[];
    points: PtVfrPoint[];
  };

  getRoutes(): PtVfrRoutesResponse {
    const { source, sourceUrl, effectiveDate, routes } = this.data;
    return { source, sourceUrl, effectiveDate, routes };
  }

  getPoints(): PtVfrPointsResponse {
    const { source, sourceUrl, effectiveDate, points } = this.data;
    return { source, sourceUrl, effectiveDate, points };
  }

  getEffectiveDate(): string | null {
    return this.data.effectiveDate;
  }
}
