apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: fs-suite
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: VATSIM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: VATSIM_CLIENT_ID
            - name: VATSIM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: VATSIM_CLIENT_SECRET
            - name: VATSIM_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: VATSIM_CALLBACK_URL
            - name: VATSIM_OAUTH_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: VATSIM_OAUTH_BASE_URL
